### ISSUE TITLE
would you please to public code？

### ISSUE THREAD

**Issue by aryanna384** [zichunzhong/zichunzhong.github.io#1]
zhong 教授您好，拜读了您的文章（DeepOrganNet）对我目前的研究工作很有启发，请问您愿意公开代码吗？

**Comment by zichunzhong** [comment]
Hi aryanna384, 

We are planning to make the code or some datasets to the public soon. Thanks for your interest in our work.

**Comment by zichunzhong** [comment]
> zhong 教授您好，拜读了您的文章（DeepOrganNet）对我目前的研究工作很有启发，请问您愿意公开代码吗？

Hi aryanna384,

We are planning to make the code or some datasets to the public soon. Thanks for your interest in our work.
